In [1]:
import torch
import torchvision
import torch_generic_nms

In [2]:
N = 100
iou_threshold = 0.5

torch.manual_seed(42)
boxes = torch.rand(N, 4).cuda()
boxes[2:4] += boxes[0, 2]  # make sure x2 >= x1 and y2 >= y1
scores = torch.rand(N).cuda()

In [3]:
torchvision_result = torchvision.ops.nms(boxes, scores, iou_threshold)
print(torchvision_result)

tensor([89, 68, 44, 12, 97, 57, 88, 70, 69, 24, 47, 48, 43, 72, 41, 14,  1, 35,
        23, 71, 33, 86, 80, 75, 30, 64, 96, 17, 62, 13, 91,  9, 90, 54, 29, 61,
        55, 79, 53, 25, 58, 83, 39,  2,  3, 93, 37, 95, 42, 20, 60, 94, 31, 73,
        87, 26, 38,  4, 98, 56,  0, 10, 40, 78, 28, 21, 36, 81, 11, 32, 16, 99,
         7, 15, 45,  8, 65, 76, 67, 74, 82, 84, 59, 85, 19, 18, 77, 63, 46, 22,
        49, 52, 66,  5,  6, 51], device='cuda:0')


In [4]:
generic_result_box = torch_generic_nms.generic_nms(boxes, scores, iou_threshold, use_iou_matrix=False)
print(generic_result_box)

tensor([89, 68, 44, 12, 97, 57, 88, 70, 69, 24, 47, 48, 43, 72, 41, 14,  1, 35,
        23, 71, 33, 86, 80, 75, 30, 64, 96, 17, 62, 13, 91,  9, 90, 54, 29, 61,
        55, 79, 53, 25, 58, 83, 39,  2,  3, 93, 37, 95, 42, 20, 60, 94, 31, 73,
        87, 26, 38,  4, 98, 56,  0, 10, 40, 78, 28, 21, 36, 81, 11, 32, 16, 99,
         7, 15, 45,  8, 65, 76, 67, 74, 82, 84, 59, 85, 19, 18, 77, 63, 46, 22,
        49, 52, 66,  5,  6, 51], device='cuda:0')


In [5]:
ious = torchvision.ops.box_iou(boxes, boxes)
generic_result_iou = torch_generic_nms.generic_nms(ious, scores, iou_threshold, use_iou_matrix=True)
print(generic_result_iou)

tensor([89, 68, 44, 12, 97, 57, 88, 70, 69, 24, 47, 48, 43, 72, 41, 14,  1, 35,
        23, 71, 33, 86, 80, 75, 30, 64, 96, 17, 62, 13, 91,  9, 90, 54, 29, 61,
        55, 79, 53, 25, 58, 83, 39,  2,  3, 93, 37, 95, 42, 20, 60, 94, 31, 73,
        87, 26, 38,  4, 98, 56,  0, 10, 40, 78, 28, 21, 36, 81, 11, 32, 16, 99,
         7, 15, 45,  8, 65, 76, 67, 74, 82, 84, 59, 85, 19, 18, 77, 63, 46, 22,
        49, 52, 66,  5,  6, 51], device='cuda:0')
